version: "3"

services:
    
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - mysql

  test:
    restart: on-failure
    container_name: app_test
    build: .
    command: npm run test
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - app

  dev_test:
    container_name: app_dev_test
    build: .
    restart: on-failure
    command: npm run test:dev:staged
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - test


  mysql:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    container_name: db_adminer
    image: adminer:latest
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080 
